services:
  mongo:
    image: mongo:7
    container_name: piensaya-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: piensaya-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: piensaya-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo-data:
